### ISSUE TITLE
How to avoid the (x.empty ? x.unwrap : someDefault) antipattern?

### ISSUE THREAD

**Issue by SimonN** [aliak00/optional#11]
This is loose brainstorming and I have no concrete suggestion.

The Java community likes to avoid calls to their Optional's `isPresent` which corresponds to D Optional's `! empty`, e.g., here:
* https://dzone.com/articles/optional-ispresent-is-bad-for-you
* http://royvanrijn.com/blog/2016/04/deprecating-optional-get/

My gut feeling is that this is a good direction. Since the D Optional behaves like a range, I'm toying around with self-rolled `orElse`, à la (untested, not copied from example!):

```
Optional!A oa = /* something */;
int n = oa.map!(a => a.getAnInt()).chain(4).front;
```

Maybe this would make for a nice abstraction in Optional, usable as `oa.dispatch.getAnInt().orElse(4)` where `orElse` unwraps the return of `dispatch.getAnInt` if that's possible or returns its argument. Or how would you write these tests where you resolve an Optional into a non-optional value or a default?

**Comment by aliak00** [comment]
Aye, it's a good direction I think so as well. A way to get at the value or default would certainly be nice to have. I was kinda hoping this would go somewhere in D -> https://github.com/dlang/phobos/pull/5154 but it seems to be stalled, so implementing something similar on `Optional!T` directly might be the way to go.

Maybe just `or`, I feel it reads quite well when applied to a variable which is an optional type already:

```
auto maybeInt = some(3)
auto i = maybeInt.or(3);

auto value = downloadSomeStuff();
auto data = value.or(dummyData);
```

I've also been considering something along the lines of std.variant's [visit](https://dlang.org/phobos/std_variant.html#.visit) and variations of that but that may be too verbose:

```
auto maybeInt = some(3)
auto i = maybeInt.visit!((int i) => i, (None) => 3);
```

As for dispatching: an Optional dispatch chain currently creates a different proxy type (`OptionalDispatcher`) that does not interfere with the members of T (so no member functions). Adding a member orElse will add this one wart which I'd prefer to avoid if possible. So currently you'd have to cast it back to an optional: `opt.dispatch.getAnInt.some` which, I'm not completely happy with, and not sure how to make it better but it maintains the "no member functions in the dispatcher" thing that I'd like to keep. Ideas on this front?

**Comment by aliak00** [comment]
heh, seems the orElse was moved to an "approved" state just a few hours ago :D

**Comment by SimonN** [comment]
I've seen the `OptionalDispatcher` in error messages before but haven't investigated deeply enough to write an `orElse` of pull-request quality. Thanks for the high-level explanation of how it differs from the normal `Optional!A`.

Yes, the Phobos `orElse` would be awesome.

The visit pattern is interesting for more complicated processing with the returned value; it allows a complete function literal. It's more verbose than `or`/`orElse` only when you want the return value unprocessed. I remember running into use cases for both, but I don't remember these exact use cases. I'll keep my eyes open.

**Comment by aliak00** [comment]
I put up this for now: https://github.com/aliak00/optional/pull/14

The visit pattern thing seems maybe a bit more rare of a use case so I'll deal with that later :)

Thanks for bringing this up!
