### ISSUE TITLE
Use defined instead of empty

### ISSUE THREAD

**Issue by skoppe** [aliak00/optional#29]
Right now because optional uses empty the `Optional!(T).init` value is non-zero. This causes - at least in webassembly - a data section with `00 00 00 01 00 00 00 00` for each T.

By swapping the logic the .init value turns into zero's and can be optimised away, thus reducing the binary with 8 bytes per T.

Is there any reason optional uses empty instead of the inverse?

**Comment by aliak00** [comment]
Good idea. No particular reason, just because empty was part of the range
interface. But can replace with defined and make empty a get property.

**Comment by skoppe** [comment]
👍
