### ISSUE TITLE
orElse returns dangling reference

### ISSUE THREAD

**Issue by anon17** [aliak00/optional#36]
When orElse receives `Optional` by value, it returns a reference from `front` that points to a stack variable and is past its lifetime when the function returns.

**Comment by anon17** [comment]
Same for all other functions.

**Comment by aliak00** [comment]
V0.18.0 a added a return annotation to .front. That doesn’t fix this?

**Comment by anon17** [comment]
Hmm... as long as front returns by ref, orElse returns a reference to stack variable?

**Comment by aliak00** [comment]
I'm not sure how to fix this without forcing a copy - which is what I'll probably do for now. I also can't seem to produce any stack error detections with LDCs ASAN using any of the functions.

https://issues.dlang.org/show_bug.cgi?id=20084

I'm open to other ideas if you have any?

**Comment by anon17** [comment]
frontOrThrow returns by ref?

**Comment by anon17** [comment]
By marking front with `return` you wanted to make it safe? Maybe explicitly mark it safe? And this can make helper functions to be inferred as safe, then you can rely on safety checks. Is frontOrThrow always safe?

**Comment by aliak00** [comment]
Ah crap. Thanks for pointing out! :) will fix.

From what I understand of return will say that the value should not out live the struct instance. Hmm yes, I can mark it @safe explicitly indeed I think. I'll try that.

frontOrThrow may or may not be safe depending on `makeThrowable`.

**Comment by anon17** [comment]
It says so, but the compiler enforces it only in `@safe` code.

**Comment by aliak00** [comment]
True dat.
Made changes, put up beta. Closing this again. Scream if anything else comes up!
