### ISSUE TITLE
std.functional.memoize fails for function returning Optional!T

### ISSUE THREAD

**Issue by pbackus** [aliak00/optional#40]
Example:

```d
import optional;
import std.functional: memoize;

Optional!int test(int n)
{
	return some(42);
}

alias testMemo = memoize!test;
```

Compiler output (DMD 2.089.0):

```
/usr/include/dmd/phobos/std/functional.d(1138,9): Error: `return` expression expected
source/app.d(9,18): Error: template instance `std.functional.memoize!(test)` error instantiating
```

**Comment by aliak00** [comment]
Thanks for reporting!! Think this is a bug in memoize.

Bug: https://issues.dlang.org/show_bug.cgi?id=20439
PR: https://github.com/dlang/phobos/pull/7311

Would you like a work around in optional in the meantime (I can have opAssign return this as a workaround it seems).

**Comment by pbackus** [comment]
Thanks for tracking this down. I can use a fixed version of memoize as a workaround for now.

I do wonder if perhaps `void opAssign` should be considered an anti-pattern in general, though. This probably isn't the only generic code out there that assumes it can use the result of an AssignExpression.

**Comment by aliak00** [comment]
Cool! I'll close this for now then.

Why `void opAssign` as an anti pattern and not `T opAssign`? Should `a = b = c` maybe be the anti pattern? And what about the usability of a setter lambda? `(a) => a = b`. Should that be mappable/foreachable/filterable?

**Comment by pbackus** [comment]
The reason `void opAssign` is (arguably) the anti-pattern is because it's different from how assignment works for built-in types. Here's the language spec's paragraph on [Assign Expressions](https://dlang.org/spec/expression.html#assign_expressions):

> For all assign expressions, the left operand must be a modifiable lvalue. The type of the assign expression is the type of the left operand, and the value is the value of the left operand after assignment occurs. The resulting expression is a modifiable lvalue.

If we want our user-defined types to be consistent with this paragraph (and for the sake of generic code, we probably do), it follows that the "correct" signature is actually `ref T opAssign`, with `this` as the return value.

**Comment by aliak00** [comment]
huh. makes sense i think. And I think I'll push a change for this too.
