### ISSUE TITLE
OptionalChain!X: Allow calls to frontOr, map, ...

### ISSUE THREAD

**Issue by SimonN** [aliak00/optional#50]
## Proposal

Allow to call `frontOr`, `map` etc. to be called on `OptionalChain!X`, not merely on `Optional!X`.

Allow `oc.foo` to work similar to `map!(e => e.foo)`.

## Reasoning
We call method `foo` on an `Optional!X` using the optional chain, `oc`:
```
class X {
    int foo() { return 43; }
}
Optional!X x = some(new X);
auto y = x.oc.foo;
```
This invokes `foo` on `x` if and only if `x` contains an `X`. A problem arises when we want to use the `y`, which is of type `OptionalChain!int`, in the typical operations that yield nonoptional values:

`int ia = y.frontOr(7);` // Error, cannot call `frontOr` on an `OptionalChain!int`, only on `Optional!int`

`int ib = (y + 0).frontOr(7);` // OK, `ib` is now 43

`int ic = y.value.frontOr(7);` // OK, `ic` is now 43

The trick to convert from `OptionalChain!int` to `Optional!int` via `+0` is surely ugly.

The public member `value` of `OptionalChain!int` that gives us the included `Optional!int` works to explicitely terminate the optional chain, but requires us to look in package optional's source code; `value` is not a documented member.

Even though `value` is alias-this-ed within `OptionalChain!T`, constructs such as `frontOr` and `map` etc. will not pick it up to iterate over the range that contains 0 or 1 values of `T`. I tested this in DMD 2.094.2, I don't know if it's a language rule or a bug. Either way, it appears to be a wart of alias-this.

According to [Your Options Do Not Match](https://www.originate.com/thinking/idiomatic-scala-your-options-do-not-match), the idiomatic way would be to prefer `std.algorithm.map` over `oc`:

`int id = x.map!(e => e.foo).frontOr(7)` // OK, `id` is now 43

The problem here is that `map` leads to verbose code. We really would like to write instead:

`int ie = x.map!foo.frontOr(7)` // Error, no global symbol `foo`

...but we need the longcut via the template lambda `e => e.foo` because of D's lookup rules.

Also, if we would have to call `x.oc` when we don't need the return type (we only want to call the function for its side effects) and `x.map!(e => e.foo)` whenever we want the return type, we'll have two different things for essentially the same operation. This is bad because we must keep the discrepancy and the two incompatible solutions in mind at all times; see also the lovely article: [What Color is Your Function?](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/)

**Comment by aliak00** [comment]
This is surprising to me. So in the code for `OptionalChain` we have this defined:

```
public Optional!T value;
alias value this;
```

But it seems that calling `someOptional.oc.someProperty.empty` results in  `Error: no property empty for type OptionalChain!T, perhaps import std.range; is needed?`

Any ideas why?

**Comment by aliak00** [comment]
I have a feeling it's soemthing to do with `opDispatch` vs `alias this` priorities which I also have a feeling was changed more recently (as in the last year or something) :/

**Comment by aliak00** [comment]
Well, not changed recently but this looks like a DMD bug :/ ... https://issues.dlang.org/show_bug.cgi?id=20233#c6

**Comment by SimonN** [comment]
Excellent detective work, you've pinpointed the `opDispatch` as the trigger of the alias-this-hiding bug.

I get from your reaction that `OptionalChain!X` shall work exactly like an `Optional!X`. The `.oc` in a functional pipeline shall disambiguate which methods will be called, in case there are symbols defined by both `Optional!X` and `X`, but it shall not prevent any call that expects an `Optional!X`.

It's possible to code around this DMD bug: `OptionalChain!X` can get its own range interface that pulls from the `Optional!X value` (best) or `frontOr()` allows `OptionalChain!X` explicitly (hackish, and doesn't fix `any`/`all` from `std.algorithm` that I also like as terminators). I'll be happy to create a PR for this the new year.

**Comment by aliak00** [comment]
Yeah, `OptionalChain!X` was supposed to work exactly as `Optional!X` at least.

As to the work around, there's this edge case problem: https://run.dlang.io/is/UGmqN9

Basically, if `X` is a range type or any other type that has the function `empty` (it's not uncommon for containers for e.g.) then the chain type `empty` will be called instead.

**Comment by aliak00** [comment]
Waitaminute! Now that I see this I can't believe I missed this:

```
struct Chain(T) {
  Opt!T value;
  auto empty() {
    static if (T has empty) {
      return some(T.empty())
    } else {
      return some(value.empty);
  }
}
```

... Or something of the sort.

I guess that is in theory the exact same behaviour of having the `alias value this` in the chainer...

**Comment by aliak00** [comment]
Just pushed this e6c48dbd192b8a0a1a0237c9ac9813d3ba36598c. I think it'll work.

**Comment by aliak00** [comment]
Feels so hackish 🤮 😆

**Comment by aliak00** [comment]
Pushed https://github.com/aliak00/optional/releases/tag/v1.2.0-beta.1 as release. Shout if it doesn't work satisfactorily. if I hear nothing for a couple weeks I'll make a non-beta release :)

**Comment by SimonN** [comment]
Right, v1.2.0-beta.1 looks good, it looks correct to prioritize `T`'s rangeness over `Optional!T`'s rangeness in the chain.

I'll give it a shot within two weekends!

**Comment by SimonN** [comment]
It looks like this had no negative side effects in my usercode.

After the dust has settled, I didn't need pure `x.oc.foo.frontOr` so often anymore; many of the old occurrences of this pattern could be improved to `x.any!(y => y.foo)` or `x.all!...`. But a few instances are still of the form `.oc.foo.frontOr` and it looks like everything is working well.

**Comment by aliak00** [comment]
Awesome! Thanks for the heads up. I'll release again!

**Comment by aliak00** [comment]
Cool! Thanks for following up! Non beta version pushed.
